default_format = "{hex}"
color_log_format = "Name: {name} | HEXA: {hexa} | RGBA: {rgba} | RGBA01: {rgba01}"

[Colors]
background = "2e3440"
Foreground = "#eceff4f0"
01 = "rgb(0.132, .251332, 1, 0)"

[Files]
Hyprland = ["~/.config/hypr/Hyprland.conf", "rgba"]
Hyprland2 = ["~/.config/hypr/Hyprland2.conf"]
Hyprland3 = "~/.config/hypr/Hyprland2.conf"
