default_format = "hex"
color_log_format = "Name: {name} | HEXA: {hexa} | RGBA: {rgba} | RGBA01: {rgba01}"
replace_files = true

[Colors]
background = "2e3440"
foreground = "#eceff4f0"

[Values]
test = 13.24
test1 = "Test1"
test2 = true
easing = "Easing"

[Files]
Hyprland = ["~/.config/hypr/Hyprland.conf"]
Hyprland2 = ["~/.config/hypr/Hyprland2.conf", "hexa"]
Hyprland3 = ["~/.config/hypr/Hyprland3.conf", "rgba"]
